import { appendFileSync, readFileSync, mkdirSync } from "fs";
import { join } from "path";

/**
 * Newline-delimited JSON log of per-PR/MR summaries generated by Louisa at merge time.
 *
 * Written to: logs/pr-summaries.jsonl  (same directory convention as releases-*.json.lines)
 *
 * Each line is a JSON object:
 * {
 *   platform:   "github" | "gitlab",
 *   repo:       "owner/repo" (GitHub) or projectId string (GitLab),
 *   number:     123,
 *   title:      "Original PR/MR title",
 *   summary:    "2-3 sentence description of what changed and why it matters.",
 *   type:       "Feature|Enhancement|Bug Fix|Refactor|Internal|Breaking Change",
 *   userImpact: "1 sentence describing what users gain or what now works correctly.",
 *   author:     "username",
 *   labels:     ["label1"],
 *   url:        "https://...",
 *   mergedAt:   "2026-04-02T10:00:00Z",
 *   tag:        "1.4.1987-success-aws-prod-platform"  // release tag this MR was processed for
 * }
 *
 * The release note webhook reads this file filtered by date range instead of
 * re-fetching and re-analysing every PR/MR at release time.
 *
 * Note: on Vercel, process.cwd() points to /var/task which is read-only.
 * Writes will fail silently; the tag webhook will fall back to the live API
 * when the file is absent.
 */

function summariesPath() {
  return join(process.cwd(), "logs", "pr-summaries.jsonl");
}

/**
 * Append one PR/MR summary entry to the log.
 * Failures are caught and logged — never throws.
 */
export function appendSummary(entry) {
  try {
    const logsDir = join(process.cwd(), "logs");
    mkdirSync(logsDir, { recursive: true });
    appendFileSync(summariesPath(), JSON.stringify(entry) + "\n", "utf8");
    console.log(`Louisa: summary logged for ${entry.platform} ${entry.repo}#${entry.number}`);
  } catch (err) {
    console.warn(`Louisa: could not write PR summary to file — ${err.message}`);
  }
}

/**
 * Read summaries for a specific release tag and repo.
 * Preferred over readSummariesInRange when a tag is known — avoids date-range fragility.
 *
 * Returns:
 *   - Array of matching entries  (file exists, even if 0 entries for this tag)
 *   - null                       (file does not exist — caller should fall back to live API)
 *
 * @param {string} repo   projectId string for GitLab, "owner/repo" for GitHub
 * @param {string} tag    release tag, e.g. "1.4.1987-success-aws-prod-platform"
 */
export function readSummariesForTag(repo, tag) {
  let raw;
  try {
    raw = readFileSync(summariesPath(), "utf8");
  } catch {
    return null;
  }

  const seen    = new Set();
  const results = [];

  for (const line of raw.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed) continue;
    let entry;
    try { entry = JSON.parse(trimmed); } catch { continue; }

    if (entry.repo !== repo || entry.tag !== tag) continue;

    const key = `${entry.repo}:${entry.number}`;
    if (seen.has(key)) continue;
    seen.add(key);
    results.push(entry);
  }

  return results;
}

/**
 * Read summaries merged between fromDate and toDate for a specific repo.
 * Use readSummariesForTag() instead when the release tag is known.
 *
 * Returns:
 *   - Array of matching entries  (file exists, even if empty for this range)
 *   - null                       (file does not exist — caller should fall back to live API)
 *
 * Deduplicates by (repo, number) so duplicate webhook deliveries are harmless.
 *
 * @param {string} repo       "owner/repo" for GitHub, projectId string for GitLab
 * @param {string} fromDate   ISO 8601 start of window (inclusive)
 * @param {string} toDate     ISO 8601 end of window (inclusive)
 */
export function readSummariesInRange(repo, fromDate, toDate) {
  let raw;
  try {
    raw = readFileSync(summariesPath(), "utf8");
  } catch {
    return null; // file not present yet — caller falls back to API
  }

  const from = new Date(fromDate);
  const to   = new Date(toDate);

  const seen    = new Set();
  const results = [];

  for (const line of raw.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed) continue;

    let entry;
    try {
      entry = JSON.parse(trimmed);
    } catch {
      continue; // skip malformed lines
    }

    if (entry.repo !== repo) continue;

    const mergedAt = new Date(entry.mergedAt);
    if (mergedAt < from || mergedAt > to) continue;

    const key = `${entry.repo}:${entry.number}`;
    if (seen.has(key)) continue;
    seen.add(key);

    results.push(entry);
  }

  return results;
}
