#!/usr/bin/env node
/**
 * Backfill Louisa's monthly release logs from already-published GitHub and
 * GitLab releases — no Claude calls, reads the existing release body/description.
 *
 * Run this once to seed the log before using draft-blog.js, or any time you
 * need to catch up on releases that were published before the log step existed.
 *
 * Usage:
 *   node scripts/backfill-log.js <github-owner> <github-repo> [--days 30]
 *
 * Env vars required:
 *   GITHUB_TOKEN       — GitHub API access
 *   GITLAB_TOKEN       — GitLab API access  (optional; skip if no GitLab project)
 *   GITLAB_PROJECT_ID  — GitLab project ID  (optional)
 */

import { appendFileSync, mkdirSync, readFileSync, existsSync, readdirSync } from "fs";
import { join } from "path";

// ── Args ──────────────────────────────────────────────────────────────────────

const rawArgs = process.argv.slice(2);
const daysIdx = rawArgs.indexOf("--days");
const days    = daysIdx !== -1 ? parseInt(rawArgs[daysIdx + 1], 10) : 30;

const positional = rawArgs.filter(
  (a, i) => !a.startsWith("--") && i !== daysIdx + 1
);
const [owner, repo] = positional;

if (!owner || !repo) {
  console.error(
    'Usage: node scripts/backfill-log.js <github-owner> <github-repo> [--days 30]'
  );
  process.exit(1);
}

const since = new Date(Date.now() - days * 24 * 60 * 60 * 1000);
console.log(
  `Backfilling releases since ${since.toISOString().slice(0, 10)} (last ${days} days)\n`
);

// ── Helpers ───────────────────────────────────────────────────────────────────

const LOUISA_FOOTER = /\n\n---\n_Release notes generated by Louisa_\s*$/;

function stripFooter(body) {
  return (body || "").replace(LOUISA_FOOTER, "").trim();
}

function extractReleaseMetadata(notes) {
  const lines = notes.split("\n");

  let theme = "";
  let foundDate = false;
  for (const line of lines) {
    if (!foundDate && line.startsWith("**")) { foundDate = true; continue; }
    if (foundDate && line.trim() && !line.startsWith("#") && !line.startsWith("---")) {
      theme = line.trim();
      break;
    }
  }

  const keyAreas = lines
    .filter((l) => l.startsWith("## ") && !l.toLowerCase().includes("breaking"))
    .map((l) => l.replace("## ", "").trim());

  const hasBreaking = lines.some((l) => l.toLowerCase().includes("breaking changes"));

  return { theme, keyAreas, breakingChanges: hasBreaking ? "Yes" : null };
}

function monthSlugFromDate(date) {
  const name = new Date(date).toLocaleString("en-US", { month: "long" }).toLowerCase();
  return `${name}-${new Date(date).getFullYear()}`;
}

/** Load all tags already present in any log file to avoid duplicates. */
function loadLoggedTags(logsDir) {
  const logged = new Set();
  if (!existsSync(logsDir)) return logged;
  for (const file of readdirSync(logsDir).filter((f) => f.endsWith(".json.lines"))) {
    for (const line of readFileSync(join(logsDir, file), "utf-8").split("\n").filter(Boolean)) {
      try { const e = JSON.parse(line); if (e.tag) logged.add(e.tag); } catch {}
    }
  }
  return logged;
}

function writeEntry(logsDir, entry) {
  mkdirSync(logsDir, { recursive: true });
  const slug    = monthSlugFromDate(entry.timestamp);
  const logPath = join(logsDir, `releases-${slug}.json.lines`);
  appendFileSync(logPath, JSON.stringify(entry) + "\n");
  console.log(`  ✓ ${entry.tag} (${entry.product}) → releases-${slug}.json.lines`);
}

// ── GitHub ────────────────────────────────────────────────────────────────────

async function fetchGitHubReleases() {
  const token = process.env.GITHUB_TOKEN;
  if (!token) {
    console.warn("GITHUB_TOKEN not set — skipping GitHub releases\n");
    return [];
  }

  const headers = {
    Authorization: `Bearer ${token}`,
    Accept: "application/vnd.github+json",
    "X-GitHub-Api-Version": "2022-11-28",
  };

  const results = [];
  let page = 1;

  while (true) {
    const res = await fetch(
      `https://api.github.com/repos/${owner}/${repo}/releases?per_page=50&page=${page}`,
      { headers }
    );
    if (!res.ok) {
      console.error(`GitHub releases API error: ${res.status} ${await res.text()}`);
      break;
    }
    const batch = await res.json();
    if (!batch.length) break;

    let doneEarly = false;
    for (const r of batch) {
      if (r.draft || r.prerelease || r.tag_name.includes("-dev")) continue;
      const publishedAt = new Date(r.published_at);
      if (publishedAt < since) { doneEarly = true; break; }

      const notes = stripFooter(r.body);
      if (!notes) continue;

      results.push({
        product:   "Arthur Engine",
        tag:       r.tag_name,
        notes,
        timestamp: r.published_at,
      });
    }

    if (doneEarly || batch.length < 50) break;
    page++;
  }

  return results;
}

// ── GitLab ────────────────────────────────────────────────────────────────────

async function fetchGitLabReleases() {
  const token     = process.env.GITLAB_TOKEN;
  const projectId = process.env.GITLAB_PROJECT_ID;

  if (!token || !projectId) {
    console.warn("GITLAB_TOKEN or GITLAB_PROJECT_ID not set — skipping GitLab releases\n");
    return [];
  }

  const headers = { "PRIVATE-TOKEN": token };
  const results = [];
  let page = 1;

  while (true) {
    const res = await fetch(
      `https://gitlab.com/api/v4/projects/${projectId}/releases?order_by=released_at&sort=desc&per_page=50&page=${page}`,
      { headers }
    );
    if (!res.ok) {
      console.error(`GitLab releases API error: ${res.status} ${await res.text()}`);
      break;
    }
    const batch = await res.json();
    if (!batch.length) break;

    let doneEarly = false;
    for (const r of batch) {
      if (!r.tag_name.endsWith("-success-aws-prod-platform")) continue;
      const releasedAt = new Date(r.released_at);
      if (releasedAt < since) { doneEarly = true; break; }

      const notes = stripFooter(r.description);
      if (!notes) continue;

      results.push({
        product:   "Arthur Platform",
        tag:       r.tag_name,
        notes,
        timestamp: r.released_at,
      });
    }

    if (doneEarly || batch.length < 50) break;
    page++;
  }

  return results;
}

// ── Main ──────────────────────────────────────────────────────────────────────

const logsDir    = join(process.cwd(), "logs");
const loggedTags = loadLoggedTags(logsDir);
console.log(`Already-logged releases to skip: ${loggedTags.size}\n`);

console.log(`Fetching GitHub releases for ${owner}/${repo}...`);
const githubReleases = await fetchGitHubReleases();
console.log(`  Found ${githubReleases.length} in window\n`);

console.log(`Fetching GitLab releases (project ${process.env.GITLAB_PROJECT_ID || "—"})...`);
const gitlabReleases = await fetchGitLabReleases();
console.log(`  Found ${gitlabReleases.length} in window\n`);

const all = [...githubReleases, ...gitlabReleases].sort(
  (a, b) => new Date(a.timestamp) - new Date(b.timestamp)
);

let written = 0;
let skipped = 0;

for (const r of all) {
  if (loggedTags.has(r.tag)) {
    console.log(`  — skipping ${r.tag} (already logged)`);
    skipped++;
    continue;
  }

  const { theme, keyAreas, breakingChanges } = extractReleaseMetadata(r.notes);

  writeEntry(logsDir, {
    product: r.product,
    tag:     r.tag,
    theme,
    keyAreas,
    breakingChanges,
    summary:   r.notes,
    timestamp: r.timestamp,
  });
  written++;
}

console.log(`\nDone. ${written} written, ${skipped} skipped.`);
if (written > 0) {
  console.log('\nNow run: node scripts/draft-blog.js "March 2026" --days 30');
}
