#!/usr/bin/env node
/**
 * One-off script to regenerate release notes for a given tag,
 * comparing against an explicit base tag.
 *
 * Usage:
 *   node scripts/regen-release.js <owner> <repo> <tag> <previousTag>
 *
 * Example:
 *   node scripts/regen-release.js arthur-ai arthur-engine 2.1.456 2.1.386
 */

import { getCommitsBetweenTags, getPullRequestsForCommits, updateReleaseBody, getReleaseByTag } from "../lib/github.js";
import { generateReleaseNotes } from "../lib/claude.js";

const [owner, repo, tag, previousTag] = process.argv.slice(2);

if (!owner || !repo || !tag || !previousTag) {
  console.error("Usage: node scripts/regen-release.js <owner> <repo> <tag> <previousTag>");
  process.exit(1);
}

console.log(`\nRegenerating release notes for ${owner}/${repo} ${tag}`);
console.log(`Comparing: ${previousTag} → ${tag}\n`);

const release = await getReleaseByTag(owner, repo, tag);
if (!release) {
  console.error(`Release not found for tag ${tag}`);
  process.exit(1);
}

const commits = await getCommitsBetweenTags(owner, repo, previousTag, tag);
console.log(`Found ${commits.length} commits`);

const shas = commits.map((c) => c.sha);
const pullRequests = await getPullRequestsForCommits(owner, repo, shas);
console.log(`Found ${pullRequests.length} merged PRs`);

const { text: notes } = await generateReleaseNotes({
  tagName: tag,
  releaseName: release.name || tag,
  commits,
  pullRequests,
  previousTag,
});

const footer = "\n\n---\n_Release notes generated by Louisa_";
await updateReleaseBody(owner, repo, release.id, notes + footer);

console.log(`\n✅ Release notes updated for ${tag}`);
console.log(`   ${release.html_url}`);
