import {
  getCommitsBetweenTags,
  getMergeRequestsForCommits,
  getPreviousReleaseTag,
  getReleaseByTag,
  createRelease,
  getProjectUrl,
} from "../lib/gitlab.js";
import { generatePlatformReleaseNotes } from "../lib/claude-platform.js";
import { postReleaseToSlack } from "../lib/slack.js";

export const config = { maxDuration: 60 };

export default async function handler(req, res) {
  if (req.method !== "POST") {
    return res.status(405).json({ error: "Method not allowed" });
  }

  // Verify GitLab webhook token
  const token = req.headers["x-gitlab-token"];
  if (token !== process.env.GITLAB_WEBHOOK_SECRET) {
    console.warn("Louisa: invalid GitLab webhook token");
    return res.status(401).json({ error: "Invalid token" });
  }

  const payload = typeof req.body === "string" ? JSON.parse(req.body) : req.body;
  const eventType = payload.object_kind || payload.event_name;

  // Only handle tag push events
  if (eventType !== "tag_push" && eventType !== "push") {
    return res.status(200).json({ skipped: true, reason: `event=${eventType}` });
  }

  // For push events, only handle tags
  const ref = payload.ref || "";
  if (!ref.startsWith("refs/tags/")) {
    return res.status(200).json({ skipped: true, reason: "not a tag" });
  }

  // Skip tag deletions
  if (payload.after === "0000000000000000000000000000000000000000") {
    return res.status(200).json({ skipped: true, reason: "tag deleted" });
  }

  const tag = ref.replace("refs/tags/", "");
  const projectId = payload.project_id || process.env.GITLAB_PROJECT_ID;

  console.log(`Louisa: GitLab tag detected — ${tag} (project ${projectId})`);

  try {
    const existing = await getReleaseByTag(projectId, tag);
    if (existing) {
      console.log(`Louisa: GitLab release already exists for ${tag}, skipping`);
      return res.status(200).json({ skipped: true, reason: "release already exists" });
    }

    const previousTag = await getPreviousReleaseTag(projectId, tag);
    console.log(`Louisa: comparing ${previousTag || "(none)"} → ${tag}`);

    const commits = await getCommitsBetweenTags(projectId, previousTag, tag);
    console.log(`Louisa: found ${commits.length} commits`);

    const shas = commits.map((c) => c.sha);
    const mergeRequests = await getMergeRequestsForCommits(projectId, shas);
    console.log(`Louisa: found ${mergeRequests.length} merged MRs`);

    const notes = await generatePlatformReleaseNotes({
      tagName: tag,
      releaseName: tag,
      commits,
      mergeRequests,
      previousTag,
    });

    const footer = "\n\n---\n_Release notes generated by Louisa_";
    const created = await createRelease(projectId, tag, tag, notes + footer);

    // Post to Slack
    const projectUrl = await getProjectUrl(projectId);
    const releaseUrl = projectUrl
      ? `${projectUrl}/-/releases/${encodeURIComponent(tag)}`
      : created._links?.self || "";

    await postReleaseToSlack(tag, releaseUrl, notes);

    console.log(`Louisa: GitLab release created for tag ${tag}`);
    return res.status(200).json({ ok: true, tag, action: "created" });
  } catch (err) {
    console.error("Louisa: error creating GitLab release", err);
    return res.status(500).json({ error: err.message });
  }
}
