import { verifyGitHubSignature } from "../lib/crypto.js";
import {
  getPRsByDateRange,
  getTagDate,
  getPreviousReleaseTag,
  getReleaseByTag,
  updateReleaseBody,
  getCommitsBetweenTags,
  getPRCommits,
  getPRFiles,
  getPRComments,
} from "../lib/github.js";
import { summarizePR, generateReleaseNotes } from "../lib/claude.js";
import { appendSummary, readSummariesInRange } from "../lib/summaries.js";
import { shouldSkipEnrichment } from "../lib/enrich.js";
import { postReleaseNotification } from "../lib/slack.js";
import { getTracer, forceFlush, activeSpan } from "../lib/otel.js";

async function dispatchGitHubReleaseAction({ tag, owner, repo }) {
  const lRepo  = process.env.LOUISA_GITHUB_REPO;  // e.g. "arthur-ai/louisa"
  const token  = process.env.GITHUB_TOKEN;
  const [lOwner, lRepoName] = lRepo.split("/");

  const res = await fetch(
    `https://api.github.com/repos/${lOwner}/${lRepoName}/dispatches`,
    {
      method:  "POST",
      headers: {
        Authorization:        `Bearer ${token}`,
        Accept:               "application/vnd.github.v3+json",
        "Content-Type":       "application/json",
      },
      body: JSON.stringify({
        event_type:     "louisa-github-release",
        client_payload: { tag, owner, repo },
      }),
    }
  );
  if (!res.ok) {
    const text = await res.text();
    throw new Error(`dispatch failed (${res.status}): ${text}`);
  }
}

export const config = { maxDuration: 60 };

export default async function handler(req, res) {
  if (req.method !== "POST") {
    return res.status(405).json({ error: "Method not allowed" });
  }

  const rawBody = typeof req.body === "string"
    ? req.body
    : JSON.stringify(req.body);

  const sig = req.headers["x-hub-signature-256"];
  if (!verifyGitHubSignature(rawBody, sig, process.env.GITHUB_WEBHOOK_SECRET)) {
    console.warn("Louisa: invalid webhook signature");
    return res.status(401).json({ error: "Invalid signature" });
  }

  const event = req.headers["x-github-event"];
  const payload = typeof req.body === "string" ? JSON.parse(req.body) : req.body;

  // Initialise the OTel provider (+ Anthropic auto-instrumentation) once per container.
  const tracer = getTracer();

  // ─── Tag push: dispatch GitHub Action to generate the release ───────────────
  // (Generation runs in a GitHub Action to avoid the 60-second Vercel timeout)
  if (event === "create" && payload.ref_type === "tag") {
    const tag   = payload.ref;
    const owner = payload.repository.owner.login;
    const repo  = payload.repository.name;

    console.log(`Louisa: new tag detected — ${tag}`);

    if (tag.includes("-dev") || tag.startsWith("sdk-")) {
      console.log(`Louisa: skipping non-primary tag ${tag}`);
      return res.status(200).json({ skipped: true, reason: "non-primary tag" });
    }

    try {
      const existing = await getReleaseByTag(owner, repo, tag);
      if (existing) {
        console.log(`Louisa: release already exists for ${tag}, skipping`);
        return res.status(200).json({ skipped: true, reason: "release already exists" });
      }

      await dispatchGitHubReleaseAction({ tag, owner, repo });
      console.log(`Louisa: dispatched louisa-github-release action for ${tag}`);
      await forceFlush();
      return res.status(200).json({ ok: true, tag, action: "dispatched" });
    } catch (err) {
      console.error("Louisa: error dispatching release action", err);
      await forceFlush();
      return res.status(500).json({ error: err.message });
    }
  }

  // ─── Manual publish: fill in empty release notes ────────────────────────────
  if (event === "release" && payload.action === "published") {
    const release = payload.release;
    if (release.draft) {
      return res.status(200).json({ skipped: true, reason: "draft" });
    }

    if (release.prerelease || release.tag_name.includes("-dev")) {
      console.log(`Louisa: skipping non-production release ${release.tag_name}`);
      return res.status(200).json({ skipped: true, reason: "non-production release" });
    }

    if (release.body && release.body.includes("Release notes generated by Louisa")) {
      console.log(`Louisa: notes already present for ${release.tag_name}, skipping`);
      return res.status(200).json({ skipped: true, reason: "notes already written" });
    }

    const owner     = payload.repository.owner.login;
    const repo      = payload.repository.name;
    const tag       = release.tag_name;
    const releaseId = release.id;

    console.log(`Louisa: processing published release ${tag} (id=${releaseId})`);

    try {
      const result = await activeSpan(tracer, "louisa.github.release.update", {
        "openinference.span.kind": "CHAIN",
        "agent.name":              "Louisa",
        "input.value":             JSON.stringify({ event: "release_published", tag, repository: `${owner}/${repo}`, releaseId }),
        "input.mime_type":         "application/json",
        "tag":                     tag,
        "repository":              `${owner}/${repo}`,
      }, async (rootSpan) => {

        const previousTag = await activeSpan(tracer, "github.get_previous_tag", {
          "openinference.span.kind": "TOOL",
          "tool.name":               "github.getPreviousReleaseTag",
          "tool.description":        "Finds the most recent release tag before the given tag to determine the commit diff range",
          "tool.parameters":         JSON.stringify({ owner: "string", repo: "string", tag: "string" }),
          "input.value":             JSON.stringify({ owner, repo, tag }),
          "input.mime_type":         "application/json",
        }, async (s) => {
          const r = await getPreviousReleaseTag(owner, repo, tag);
          s.setAttribute("output.value",     r || "(none)");
          s.setAttribute("output.mime_type", "text/plain");
          return r;
        });
        console.log(`Louisa: comparing ${previousTag || "(none)"} → ${tag}`);

        const commits = await activeSpan(tracer, "github.get_commits", {
          "openinference.span.kind": "TOOL",
          "tool.name":               "github.getCommitsBetweenTags",
          "tool.description":        "Retrieves all commits between two tags to identify what changed in this release",
          "tool.parameters":         JSON.stringify({ owner: "string", repo: "string", base: "string", head: "string" }),
          "input.value":             JSON.stringify({ owner, repo, base: previousTag, head: tag }),
          "input.mime_type":         "application/json",
        }, async (s) => {
          const r = await getCommitsBetweenTags(owner, repo, previousTag, tag);
          s.setAttribute("output.value",     JSON.stringify(r.map(c => ({ sha: c.sha.slice(0, 7), message: c.message }))));
          s.setAttribute("output.mime_type", "application/json");
          return r;
        });
        console.log(`Louisa: found ${commits.length} commits`);

        const [fromTagDate, toTagDate] = await Promise.all([
          previousTag ? getTagDate(owner, repo, previousTag) : Promise.resolve(null),
          getTagDate(owner, repo, tag),
        ]);
        const pullRequests = await activeSpan(tracer, "github.get_pull_requests", {
          "openinference.span.kind": "TOOL",
          "tool.name":               "github.getPRsForRelease",
          "tool.description":        "Resolves merged PRs for the release window — reads pre-computed summaries from log if available, falls back to GitHub Search API",
          "tool.parameters":         JSON.stringify({ owner: "string", repo: "string", fromDate: "string", toDate: "string" }),
          "input.value":             JSON.stringify({ owner, repo, fromDate: fromTagDate, toDate: toTagDate }),
          "input.mime_type":         "application/json",
        }, async (s) => {
          if (previousTag && !fromTagDate) {
            console.warn(`Louisa: could not resolve date for previous tag ${previousTag} — skipping PR fetch to avoid epoch-range query`);
            s.setAttribute("output.value",     "[]");
            s.setAttribute("output.mime_type", "application/json");
            return [];
          }
          const from = fromTagDate || new Date(0).toISOString();
          const to   = toTagDate
            ? new Date(new Date(toTagDate).getTime() + 10 * 60 * 1000).toISOString()
            : new Date().toISOString();

          // Try the local summaries log first — populated at PR merge time
          const cached = readSummariesInRange(`${owner}/${repo}`, from, to);
          if (cached !== null) {
            console.log(`Louisa: using ${cached.length} pre-computed PR summaries from log`);
            s.setAttribute("output.value",     JSON.stringify(cached.map(e => ({ number: e.number, title: e.title }))));
            s.setAttribute("output.mime_type", "application/json");
            return cached.map((entry) => ({
              number: entry.number,
              title:  entry.title,
              body:   `**Summary:** ${entry.summary}\n\n**User Impact:** ${entry.userImpact}\n\n**Type:** ${entry.type}`,
              author: entry.author,
              labels: entry.labels || [],
              url:    entry.url,
            }));
          }

          // Summaries log absent — fall back to live GitHub Search API
          console.log(`Louisa: summaries log not found, fetching PRs from GitHub API`);
          const r = await getPRsByDateRange(owner, repo, from, to);
          s.setAttribute("output.value",     JSON.stringify(r.map(pr => ({ number: pr.number, title: pr.title }))));
          s.setAttribute("output.mime_type", "application/json");
          return r;
        });
        console.log(`Louisa: found ${pullRequests.length} merged PRs`);

        // AnthropicInstrumentation auto-creates an LLM span as a child of rootSpan.
        const { text: notes } = await generateReleaseNotes({ tagName: tag, releaseName: release.name || tag, commits, pullRequests, previousTag });

        const footer = "\n\n---\n_Release notes generated by Louisa_";
        await activeSpan(tracer, "github.update_release", {
          "openinference.span.kind": "TOOL",
          "tool.name":               "github.updateReleaseBody",
          "tool.description":        "Updates an existing GitHub Release body with the AI-generated release notes",
          "tool.parameters":         JSON.stringify({ owner: "string", repo: "string", releaseId: "integer", body: "string" }),
          "input.value":             JSON.stringify({ owner, repo, releaseId }),
          "input.mime_type":         "application/json",
        }, async (s) => {
          await updateReleaseBody(owner, repo, releaseId, notes + footer);
          s.setAttribute("output.value",     "updated");
          s.setAttribute("output.mime_type", "text/plain");
        });

        const releaseUrl = release.html_url;
        await activeSpan(tracer, "slack.post_notification", {
          "openinference.span.kind": "TOOL",
          "tool.name":               "notifications.postReleaseNotification",
          "tool.description":        "Posts a release notification to configured channels (Slack and/or Teams) via Incoming Webhook",
          "tool.parameters":         JSON.stringify({ tag: "string", releaseUrl: "string", notes: "string" }),
          "input.value":             JSON.stringify({ tag, releaseUrl }),
          "input.mime_type":         "application/json",
        }, async (s) => {
          await postReleaseNotification(tag, releaseUrl, notes);
          s.setAttribute("output.value",     "notification sent");
          s.setAttribute("output.mime_type", "text/plain");
        });

        rootSpan.setAttribute("output.value",     releaseUrl);
        rootSpan.setAttribute("output.mime_type", "text/plain");
        console.log(`Louisa: release ${tag} updated successfully`);
        return { ok: true, tag, action: "updated" };
      });

      await forceFlush();
      return res.status(200).json(result);
    } catch (err) {
      console.error("Louisa: error updating release", err);
      await forceFlush();
      return res.status(500).json({ error: err.message });
    }
  }

  // ─── PR merged: generate summary and append to log ───────────────────────────
  if (
    event === "pull_request" &&
    payload.action === "closed" &&
    payload.pull_request?.merged === true
  ) {
    const pr       = payload.pull_request;
    const owner    = payload.repository.owner.login;
    const repo     = payload.repository.name;
    const prNumber = pr.number;

    if (pr.draft) {
      return res.status(200).json({ skipped: true, reason: "draft PR" });
    }

    const { skip, reason: skipReason } = shouldSkipEnrichment({
      title:          pr.title,
      authorUsername: pr.user?.login ?? "",
      authorType:     pr.user?.type  ?? "",
    });
    if (skip) {
      console.log(`Louisa: skipping PR #${prNumber} — ${skipReason}`);
      return res.status(200).json({ skipped: true, reason: skipReason });
    }

    console.log(`Louisa: summarising merged PR #${prNumber} — "${pr.title}"`);

    try {
      const result = await activeSpan(tracer, "louisa.github.summarize_pr", {
        "openinference.span.kind": "CHAIN",
        "agent.name":              "Louisa",
        "input.value":             JSON.stringify({ event: "pr_merged", prNumber, repository: `${owner}/${repo}` }),
        "input.mime_type":         "application/json",
        "pr_number":               String(prNumber),
        "repository":              `${owner}/${repo}`,
      }, async (rootSpan) => {

        const [commits, files, comments] = await activeSpan(tracer, "github.get_pr_context", {
          "openinference.span.kind": "TOOL",
          "tool.name":               "github.getPRContext",
          "tool.description":        "Fetches commits, changed files, and review comments from the merged PR",
          "tool.parameters":         JSON.stringify({ owner: "string", repo: "string", prNumber: "integer" }),
          "input.value":             JSON.stringify({ owner, repo, prNumber }),
          "input.mime_type":         "application/json",
        }, async (s) => {
          const [c, f, co] = await Promise.all([
            getPRCommits(owner, repo, prNumber),
            getPRFiles(owner, repo, prNumber),
            getPRComments(owner, repo, prNumber),
          ]);
          s.setAttribute("output.value",     JSON.stringify({ commits: c.length, files: f.length, comments: co.length }));
          s.setAttribute("output.mime_type", "application/json");
          return [c, f, co];
        });

        const { summary, type, userImpact } = await activeSpan(tracer, "louisa.summarize_pr", {
          "openinference.span.kind": "TOOL",
          "tool.name":               "louisa.summarizePR",
          "tool.description":        "Calls Claude to generate a compact summary of the PR for the summaries log",
          "tool.parameters":         JSON.stringify({ platform: "string", title: "string", body: "string", commits: "array", files: "array", comments: "array" }),
          "input.value":             JSON.stringify({ prNumber, title: pr.title }),
          "input.mime_type":         "application/json",
        }, async (s) => {
          const r = await summarizePR({
            platform: "github",
            title:    pr.title,
            body:     pr.body || "",
            commits,
            files,
            comments,
          });
          s.setAttribute("output.value",     r.summary);
          s.setAttribute("output.mime_type", "text/plain");
          return r;
        });

        appendSummary({
          platform:   "github",
          repo:       `${owner}/${repo}`,
          number:     prNumber,
          title:      pr.title,
          summary,
          type,
          userImpact,
          author:     pr.user?.login,
          labels:     (pr.labels || []).map((l) => l.name),
          url:        pr.html_url,
          mergedAt:   pr.merged_at,
        });

        rootSpan.setAttribute("output.value",     `PR #${prNumber} summarised`);
        rootSpan.setAttribute("output.mime_type", "text/plain");
        console.log(`Louisa: PR #${prNumber} summarised (${type})`);
        return { ok: true, prNumber, action: "summarised", type };
      });

      await forceFlush();
      return res.status(200).json(result);
    } catch (err) {
      console.error(`Louisa: error summarising PR #${prNumber}`, err);
      await forceFlush();
      return res.status(500).json({ error: err.message });
    }
  }

  return res.status(200).json({ skipped: true, reason: `event=${event}` });
}
