import { verifyGitHubSignature } from "../lib/crypto.js";
import {
  getCommitsBetweenTags,
  getPullRequestsForCommits,
  getPreviousReleaseTag,
  getReleaseByTag,
  createRelease,
  updateReleaseBody,
} from "../lib/github.js";
import { generateReleaseNotes } from "../lib/claude.js";
import { postReleaseToSlack } from "../lib/slack.js";

export const config = { maxDuration: 60 };

export default async function handler(req, res) {
  if (req.method !== "POST") {
    return res.status(405).json({ error: "Method not allowed" });
  }

  const rawBody = typeof req.body === "string"
    ? req.body
    : JSON.stringify(req.body);

  const sig = req.headers["x-hub-signature-256"];
  if (!verifyGitHubSignature(rawBody, sig, process.env.GITHUB_WEBHOOK_SECRET)) {
    console.warn("Louisa: invalid webhook signature");
    return res.status(401).json({ error: "Invalid signature" });
  }

  const event = req.headers["x-github-event"];
  const payload = typeof req.body === "string" ? JSON.parse(req.body) : req.body;

  if (event === "create" && payload.ref_type === "tag") {
    const tag = payload.ref;
    const owner = payload.repository.owner.login;
    const repo = payload.repository.name;

    console.log(`Louisa: new tag detected — ${tag}`);

    try {
      const existing = await getReleaseByTag(owner, repo, tag);
      if (existing) {
        console.log(`Louisa: release already exists for ${tag}, skipping`);
        return res.status(200).json({ skipped: true, reason: "release already exists" });
      }

      const previousTag = await getPreviousReleaseTag(owner, repo, tag);
      console.log(`Louisa: comparing ${previousTag || "(none)"} → ${tag}`);

      const commits = await getCommitsBetweenTags(owner, repo, previousTag, tag);
      console.log(`Louisa: found ${commits.length} commits`);

      const shas = commits.map((c) => c.sha);
      const pullRequests = await getPullRequestsForCommits(owner, repo, shas);
      console.log(`Louisa: found ${pullRequests.length} merged PRs`);

      const notes = await generateReleaseNotes({
        tagName: tag,
        releaseName: tag,
        commits,
        pullRequests,
        previousTag,
      });

      const footer = "\n\n---\n_Release notes generated by Louisa_";
      const created = await createRelease(owner, repo, tag, tag, notes + footer);

      const releaseUrl = created.html_url;
      await postReleaseToSlack(tag, releaseUrl, notes);

      console.log(`Louisa: release created for tag ${tag}`);
      return res.status(200).json({ ok: true, tag, action: "created" });
    } catch (err) {
      console.error("Louisa: error creating release from tag", err);
      return res.status(500).json({ error: err.message });
    }
  }

  if (event === "release" && payload.action === "published") {
    const release = payload.release;
    if (release.draft) {
      return res.status(200).json({ skipped: true, reason: "draft" });
    }

    if (release.body && release.body.includes("Release notes generated by Louisa")) {
      console.log(`Louisa: notes already present for ${release.tag_name}, skipping`);
      return res.status(200).json({ skipped: true, reason: "notes already written" });
    }

    const owner = payload.repository.owner.login;
    const repo = payload.repository.name;
    const tag = release.tag_name;
    const releaseId = release.id;

    console.log(`Louisa: processing published release ${tag} (id=${releaseId})`);

    try {
      const previousTag = await getPreviousReleaseTag(owner, repo, tag);
      console.log(`Louisa: comparing ${previousTag || "(none)"} → ${tag}`);

      const commits = await getCommitsBetweenTags(owner, repo, previousTag, tag);
      console.log(`Louisa: found ${commits.length} commits`);

      const shas = commits.map((c) => c.sha);
      const pullRequests = await getPullRequestsForCommits(owner, repo, shas);
      console.log(`Louisa: found ${pullRequests.length} merged PRs`);

      const notes = await generateReleaseNotes({
        tagName: tag,
        releaseName: release.name || tag,
        commits,
        pullRequests,
        previousTag,
      });

      const footer = "\n\n---\n_Release notes generated by Louisa_";
      await updateReleaseBody(owner, repo, releaseId, notes + footer);

      const releaseUrl = release.html_url;
      await postReleaseToSlack(tag, releaseUrl, notes);

      console.log(`Louisa: release ${tag} updated successfully`);
      return res.status(200).json({ ok: true, tag, action: "updated" });
    } catch (err) {
      console.error("Louisa: error updating release", err);
      return res.status(500).json({ error: err.message });
    }
  }

  return res.status(200).json({ skipped: true, reason: `event=${event}` });
}
