import { verifyGitHubSignature } from "../lib/crypto.js";
import {
  getCommitsBetweenTags,
  getPullRequestsForCommits,
  getPreviousReleaseTag,
  updateReleaseBody,
} from "../lib/github.js";
import { generateReleaseNotes } from "../lib/claude.js";

export const config = { maxDuration: 60 };

export default async function handler(req, res) {
  if (req.method !== "POST") {
    return res.status(405).json({ error: "Method not allowed" });
  }

  const rawBody = typeof req.body === "string"
    ? req.body
    : JSON.stringify(req.body);

  const sig = req.headers["x-hub-signature-256"];
  if (!verifyGitHubSignature(rawBody, sig, process.env.GITHUB_WEBHOOK_SECRET)) {
    console.warn("Louisa: invalid webhook signature");
    return res.status(401).json({ error: "Invalid signature" });
  }

  const event = req.headers["x-github-event"];
  const payload = typeof req.body === "string" ? JSON.parse(req.body) : req.body;

  if (event !== "release" || payload.action !== "published") {
    return res.status(200).json({ skipped: true, reason: `event=${event}, action=${payload.action}` });
  }

  const release = payload.release;
  if (release.draft) {
    return res.status(200).json({ skipped: true, reason: "draft or prerelease" });
  }

  const owner = payload.repository.owner.login;
  const repo = payload.repository.name;
  const tag = release.tag_name;
  const releaseId = release.id;

  console.log(`Louisa: processing release ${tag} (id=${releaseId})`);

  try {
    const previousTag = await getPreviousReleaseTag(owner, repo, tag);
    console.log(`Louisa: comparing ${previousTag || "(none)"} → ${tag}`);

    const commits = await getCommitsBetweenTags(owner, repo, previousTag, tag);
    console.log(`Louisa: found ${commits.length} commits`);

    const shas = commits.map((c) => c.sha);
    const pullRequests = await getPullRequestsForCommits(owner, repo, shas);
    console.log(`Louisa: found ${pullRequests.length} merged PRs`);

    const notes = await generateReleaseNotes({
      tagName: tag,
      releaseName: release.name,
      commits,
      pullRequests,
      previousTag,
    });

    const header = `# ${release.name || tag}\n\n`;
    const footer = `\n\n---\n_Release notes generated by Louisa 🤖_`;
    const fullBody = header + notes + footer;

    await updateReleaseBody(owner, repo, releaseId, fullBody);
    console.log(`Louisa: release ${tag} updated successfully`);

    return res.status(200).json({ ok: true, tag, notesLength: notes.length });
  } catch (err) {
    console.error("Louisa: error processing release", err);
    return res.status(500).json({ error: err.message });
  }
}
